### PR TITLE
use github logo4g instead of google code.

### PR DESCRIPTION
**Pull request by gwenzek**

### CODE REVIEW

**Comment by gwenzek** [comment]
It needs #63 to be merged before the integration could work

**Comment by quarnster** [comment]
#63 merged. I think that merge makes this change obsolete. Thanks though! :)

**Comment by gwenzek** [comment]
I don't know where to post this as their is no issues, but I spotted a bug
in the CompleteAt in C#.

When looking for a Type the completion will only look up namespaces
imported with the "using" statement, but won't look up the current
namespace.

But if I explicitly import the namespace I'm in, the completion will work.

I think it could be fixed by prepending the current namespace to the
`using` list, but I didn't manage to extract this information from the
parsing tree.
The RootNode() seems to have only "using" nodes inside.

If someone with better knowledge of the framework could give some pointers
I'll be really thankful.

**Comment by quarnster** [comment]
@gwenzek, The [using](https://github.com/quarnster/completion/blob/973ceda3661dd1e43fadf5297726ac2499d5e785/net/net.go#L190) sub-tree is created with only the [using directives](https://github.com/quarnster/completion/blob/973ceda3661dd1e43fadf5297726ac2499d5e785/net/net.go#L187).

Similarly, [r](https://github.com/quarnster/completion/blob/973ceda3661dd1e43fadf5297726ac2499d5e785/net/net.go#L200) only contains the sub-tree of the [complete](https://github.com/quarnster/completion/blob/973ceda3661dd1e43fadf5297726ac2499d5e785/net/net.go#L197) parse tree.

How these parse trees are created is defined in [csharp.peg](https://github.com/quarnster/completion/blob/master/net/csharp/csharp.peg), together with the [ignore_csharp](https://github.com/quarnster/completion/blob/5c7b744dd50dec4fa42c10f868e7521cbae3f127/build/Makefile#L11) list in the makefile. The ignore list is a list of directives to not create a node for but their children might have nodes created.

What I'd probably do is to first call:
data := scopes.[Substr](http://godoc.org/github.com/quarnster/completion/util/scopes#Substr)(args.Location.File.Contents, scopes.[Visibility](http://godoc.org/github.com/quarnster/completion/util/scopes#Visibility)(args.Location))
to collapse the data to parse into only the relevant scopes. Then you might have to further remove irrelevant scopes to make it easier for the parser, as it's not very competent. And finally you try to parse the full file via:
```go
var p CSHARP
p.Parse(data)
root := p.RootNode()
root.Simplify()
```
Hopefully root will contain some "Namespace" nodes now, otherwise you'll have to tweak csharp.peg and any "reduction" utility functions until it is able to parse the file correctly and give you the nodes you need.

**Comment by gwenzek** [comment]
Thanks,

The Namespace node wasn't appearing in the tree because of a bug in the
.peg (identifier instead of dotted identifier) .

I'll make a pull request soon, need more testing.

**Pull request closed without merging**
